[package]
name = "jy-derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
anyhow = "1.0.51"
syn = "1.0.82"
quote = "1.0.10"
itertools = "0.10.3"

